export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const PROFILE_DATA_REQUEST = 'PROFILE_DATA_REQUEST';
export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const PROFILE_DATA_FAILURE = 'PROFILE_DATA_SUCCESS';
